{"tag": "function", "depth": 1, "time": 1616071852.035396, "data": {"name": "stop_app", "call_args": {"package": "jd.cdyjy.overseas.market.indonesia"}, "start_time": 1616071851.428691, "ret": null, "end_time": 1616071852.0353558}}
{"tag": "function", "depth": 1, "time": 1616071853.4437199, "data": {"name": "home", "call_args": {}, "start_time": 1616071852.03566, "ret": null, "end_time": 1616071853.443653}}
{"tag": "function", "depth": 1, "time": 1616071855.336235, "data": {"name": "start_app", "call_args": {"package": "jd.cdyjy.overseas.market.indonesia", "activity": null}, "start_time": 1616071853.444001, "ret": null, "end_time": 1616071855.336171}}
{"tag": "function", "depth": 2, "time": 1616071860.0499241, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1616071855.336663, "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/airtest/cli/runner.py\", line 70, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"/Users/xiaoyao62/airtest/airtest_jdid/testIsDisplayByList.air/testIsDisplayByList.py\", line 21, in <module>\n    wait(Template(r\"tpl1616054670703.png\", record_pos=(-0.231, -0.11), resolution=(1080, 1920)), timeout=30, interval=2, intervalfunc=notfound)\nNameError: name 'notfound' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/airtest/utils/logwraper.py\", line 90, in wrapper\n    res = f(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/airtest/core/cv.py\", line 106, in try_log_screen\n    aircv.imwrite(filepath, screen, quality, max_size=max_size)\n  File \"/usr/local/lib/python3.7/site-packages/airtest/aircv/aircv.py\", line 33, in imwrite\n    pil_img = cv2_2_pil(img)\n  File \"/usr/local/lib/python3.7/site-packages/airtest/aircv/utils.py\", line 68, in cv2_2_pil\n    cv2_im = cv2.cvtColor(cv2_image, cv2.COLOR_BGR2RGB)\ncv2.error: OpenCV(4.5.1) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-p8djv5ll/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'\n\n", "end_time": 1616071860.0499}}
